spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.Datasource
    tomcat:
      # jdbc-interceptors: 
      default-auto-commit: false
      test-on-borrow: true
      test-while-idle: true
      max-age: 60000
      initial-size: 3
      max-active: 100
    #driver-class-name: asdad
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    application:
      name: com-payment-sample
    profiles:
      active: dev
    
    
  data: 
    redis:
      repositories:
        enabled: false
        
  cache:
    type: redis
    redis:
      time-to-live: 60000
    
    jms:
      pub-sub-domain: false
    
server:
  port: 8090 
  servlet:
    context-path: /com/payment/sample/v1
  ssl:
    enabled: false
      
cors:
  switchOn: true
  origins:
  
springdoc:
  swagger-ui:
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
    disable-swagger-default-url: true
    host: ${server.servlet.context-path}
    title: Book Payment Sample API Specification Module
    description: Book Payment Sample API Specification Module
  api-docs:
    enabled: true
    resolve-schema-properties: true
    writer-with-default-pretty-printer: true
    
  #pagehelper:
    
  